steps:
- name: 'python'
  args: ['sh', 'ci/integrate.sh']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_APP', 'container/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - '$_SERVICE'
    - '--allow-unauthenticated'
    - '--platform=managed'
    - '--region=us-central1'
    - '--image=gcr.io/$PROJECT_ID/$_APP'
    - '--add-cloudsql-instances=$_SQL_CONN'

